"""empty message

Revision ID: e33561a1e6f8
Revises: b5e9804ba93c
Create Date: 2023-04-19 18:03:01.153364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33561a1e6f8'
down_revision = 'b5e9804ba93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disabled_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.String(length=20), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disabled_slot')
    # ### end Alembic commands ###
